SSAD/Simple-Quiz-Portal/config/routes.rb
Rails.application.routes.draw do
  
  get '/scoreboard', to: 'score_board#show'
  
  post '/retake', to: 'quizzes#retake'
  
  resources :users  
  get '/scores', to: 'leader_boards#showAll'

  get '/genre/:topic', to: 'leader_boards#showGenreWise'

  get '/scores/:id', to: 'leader_boards#showTopicWise'

  get '/genres', to: 'quizzes#showGenres'

  get '/genres/:genre', to: 'quizzes#showTopics'

  get '/:genre/:topic', to: 'quizzes#showQuestions'

  post '/updateScore', to: 'quizzes#updateScore'

  post '/updateMultipleScore', to: 'quizzes#updateMultipleScore'
  
  get '/editdbs', to: 'operations#editDbs'

  post '/addTopic', to: 'operations#addTopic'

  post '/delTopic', to: 'operations#delTopic'

  post '/addSubTopic', to: 'operations#addSubTopic'

  post '/delSubTopic', to: 'operations#delSubTopic'

  post '/addQuestion', to:  'operations#addQuestion'

  post '/delQuestion', to: 'operations#delQuestion'

  post '/addMultipleQuestion', to: 'operations#addMultipleQuestion'

  post '/delMultipleQuestion', to: 'operations#delMultipleQuestion'

  get 'sessions/new'
  
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/google', to: 'sessions#google'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SSAD/Simple-Quiz-Portal/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def showGenres
    @user = current_user
    @genres = Genre.distinct.pluck(:parent)
  end
  
  def showTopics
    @user = current_user
    @genre = Genre.distinct.pluck(:parent)
    @genres = Genre.where(parent: params[:genre])
    @head = params[:genre]
  end

  def showQuestions
    @user = current_user
    @touch = Touch.new
    @single_choices = SingleChoice.new
    @genre = Genre.find_by(parent: params[:genre], subtype: params[:topic])
    @single_answers = SingleAnswer.where(genre_id: @genre.id).all
    @touches = Touch.find_by(genre_id: @genre.id,user_id: current_user.id)
    
    if !@touches
      @touches = Touch.new(genre_id: @genre.id,user_id: current_user.id,score:0)
      @touches.save
    end
    @topics = Genre.where(parent: @genre.parent)

    @multiple_choices = MultipleChoice.new
    @multiple_answers = MultipleAnswer.where(genre_id: @genre.id).all

    @marked_single = []
    @single_answers.each do |t|
      a = SingleChoice.where(touch_id: @touches[:id],single_answer_id: t[:id])
      if a.length > 0
        if a[0][:answer] == t[:answer]
          @marked_single.push("c")
        else
          @marked_single.push("i")
        end
      else
        @marked_single.push("u")
      end
    end

    @marked_multiple = []
    @multiple_answers.each do |t|
      b = MultipleChoice.where(touch_id: @touches[:id], multiple_answer_id: t[:id])
      if b.length > 0
        if check2(b,t)
          @marked_multiple.push("c")
        else
          @marked_multiple.push("i")
        end
      else
        @marked_multiple.push("u")
      end
    end
  end

  def updateScore
    @posted = params.require(:single_choice)
    @question = SingleAnswer.find(@posted[:single_answer_id])
    
    @single_choices = SingleChoice.find_by(@posted.permit(:touch_id,:single_answer_id))

    if !!@single_choices
      if @question[:answer] != @posted[:answer]
        if @single_choices.answer == @question[:answer]
          decrement(@posted[:touch_id])
        end
      else 
        if @single_choices.answer != @posted[:answer]
          increment(@posted[:touch_id])
        end
      end
      @single_choices.answer = @posted[:answer]
      @single_choices.save
        
    else
      @single_choices = SingleChoice.new(@posted.permit(:touch_id, :single_answer_id, :answer))
      if @question[:answer] == @posted[:answer]
        increment(@posted[:touch_id])
      end
      @single_choices.save
    end
    @temp = Genre.find(Touch.find(@single_choices[:touch_id])[:genre_id])
    return redirect_to ("/"  +  @temp[:parent] + "/" + @temp[:subtype] )
  end

  def updateMultipleScore
    @posted = params.require(:multiple_choice)
    @question = MultipleAnswer.find(@posted[:multiple_answer_id])
    
    @multiple_choices = MultipleChoice.where(@posted.permit(:touch_id,:multiple_answer_id))
    
    if @multiple_choices.length > 0
      if !check(@question,@posted)
        if check2(@multiple_choices,@question)
          decrement(@posted[:touch_id])
        end
      else
        if !check2(@multiple_choices, @posted)
          increment(@posted[:touch_id])
        end
      end
      @multiple_choices[0][:answer1] = @posted[:answer1]
      @multiple_choices[0][:answer2] = @posted[:answer2]
      @multiple_choices[0][:answer3] = @posted[:answer3]
      @multiple_choices[0][:answer4] = @posted[:answer4]
      
      @multiple_choices[0].save
        
    else
      @multiple_choices = []
      @multiple_choices.push(MultipleChoice.new(@posted.permit(:touch_id, :multiple_answer_id, :answer1,:answer2, :answer3,:answer4)))
      if check(@question, @posted)
        increment(@posted[:touch_id])
      end
      @multiple_choices[0].save
    end
    @temp = Genre.find(Touch.find(@multiple_choices[0][:touch_id])[:genre_id])
    return redirect_to ("/"  +  @temp[:parent] + "/" + @temp[:subtype] )
  end

  def check(question, posted)
    ( a(@question[:answer1]) == a(@posted[:answer1]) ) && ( a(@question[:answer2]) == a(@posted[:answer2])) && ( a(@question[:answer3]) == a(@posted[:answer3]) ) && ( a(@question[:answer4]) == a(@posted[:answer4]))
  end

  
  def check2(question, posted)
    ( a(question[0][:answer1]) == a(posted[:answer1]) ) && ( a(question[0][:answer2]) == a(posted[:answer2])) && ( a(question[0][:answer3]) == a(posted[:answer3]) ) && ( a(question[0][:answer4]) == a(posted[:answer4]))
  end

  def a(m)
    if m == "true"
      true
    else
      if m == "false"
        false
      else
        m
      end
    end
  end

#  def check2(choices, posted)

    
  def increment(touch_id)
    touch = Touch.find(touch_id)
    touch.score += 1
    touch.save
    touch.reload
    user = User.find(touch.user_id)
    user.score += 1
    user.save
  end

  def decrement(touch_id)
    touch = Touch.find(touch_id)
    touch.score -= 1
    touch.save
    touch.reload
    user = User.find(touch.user_id)
    user.score -= 1
    user.save
  end

  def retake
    @touch = Touch.where(params.require(:touch).permit(:user_id, :genre_id))[0]
    MultipleChoice.where(touch_id: @touch[:id]).destroy_all
    SingleChoice.where(touch_id: @touch[:id]).destroy_all
    @user = User.find(current_user[:id])
    @user.score -= @touch[:score]
    @user.save
    @genre = Genre.find(@touch.genre_id)
    @touch.destroy
    redirect_to "/" + @genre[:parent] + "/" + @genre[:subtype]
  end

end

SSAD/Simple-Quiz-Portal/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

SSAD/Simple-Quiz-Portal/app/views/quizzes/showGenres.html.erb
<% provide(:title,"Leader Board") %>
<ul align="center">
    <br/><br/><br/>
    <h1 align="center">Genres</h1>
    <% @genres.each do |p| %>
	<li align="center"><%= link_to p, "/genres/" + p %></li>
    <% end  %>
    
</ul>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<p align="center" style="color:red">Questions in Red color indicate incorrect answers have been provided</p>
<p align="center" style="color:green">Questions in Green color indicate correct answers have been provided</p>
<p align="center" style="color:blue">Questions unattempted are in blue</p>

SSAD/Simple-Quiz-Portal/app/views/quizzes/showQuestions.html.erb
<% provide(:title, @genre.parent + " | "  + @genre.subtype) %>
<h2><%= @genre.parent %></h2>

<div style="float:right" >
    <h2>Score: <%= @touches.score%></h2>

<%= form_for(@touch, url: retake_path) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <p style="display:none"><%= f.select :genre_id, [@touches.genre_id] %></p>
    <p style="display:none"><%= f.select :user_id, [@touches.user_id] %></p>
    <%= f.submit "Retake Quiz", class: "btn btn-primary" %>
<% end %>  
</div>


<ul>
    <% @topics.each do |t| %>
	<li><%= link_to t.subtype, "/" + @genre.parent + "/" + t.subtype%></li>
    <% end  %>
</ul>
<script>
 var func = function() {
     document.getElementById("questions_single").style.display = "block";
     document.getElementById("questions_multiple").style.display = "none";
     document.getElementById("hide").style.backgroundColor = "blue";
     document.getElementById("hide2").style.backgroundColor = "grey";
 }
 var func2 = function() {
     document.getElementById("questions_single").style.display = "none";
     document.getElementById("questions_multiple").style.display = "block";
     document.getElementById("hide").style.backgroundColor = "grey";
     document.getElementById("hide2").style.backgroundColor = "blue";
 }
 
</script>
<div id="center4" >
<ul>
    <li onclick="func()" id="hide">SingleAnswer Type</li>
    <li onclick="func2()" id="hide2">MultipleAnswer Type</li>
</ul>
</div>
<div id="center" >
    <div id="questions_single">
	<h1>Questions under <%= @genre.subtype %></h1>
<ul >
	<% @single_answers.zip(@marked_single).each do |t,m| %>
	    <p class="<%= m -%>"><%= t.question %></p>
	    <%= form_for(@single_choices, url: updateScore_path) do |f| %>
		<%= render 'shared/error_messages' %>

		<img id="<%= "s_" + t.id.to_s %>" src="" width=420/>
		<br/>
		<script>
		 url = "<%=t.url %>";
		 if( url.match(/\.(jpeg|jpg|gif|png)$/) != null ){
		     document.getElementById('s_' + "<%= t.id.to_s %>").src = "<%=t.url %>";
		 }		 
		 else if(  url.match(/\.(flac|ogg|mp3|wav)$/) != null ){
		     document.getElementById('sa_' + "<%= t.id.to_s %>").src = "<%=t.url %>";
		     document.getElementById('sa_' + "<%= t.id.to_s %>").type = "<%=t.url %>".split('.').pop();
		 }
		 
		</script>

		<%= f.label :your_answer %>
		<%= f.select :answer, [t.option1, t.option2, t.option3, t.option4]  %>
		
		<p style="display:none"><%= f.select :single_answer_id, [t.id] %></p>
		<p style="display:none"><%= f.select :touch_id, [@touches.id] %></p>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	    <% end %>  
	<% end %>
	</li>
</ul>
    </div>
    <div id="questions_multiple">
	<h1>Questions under <%= @genre.subtype %></h1>
	<ul >
	    <% @multiple_answers.zip(@marked_multiple).each do |t,v| %>
		<li><p class="<%= v -%>"><%= t.question %></p>
		    <%= form_for(@multiple_choices, url: updateMultipleScore_path) do |f| %>
			<%= render 'shared/error_messages' %>
			<img id="<%= "m_" + t.id.to_s %>" src=""/>
		<br/>
		<script>
		 url = "<%=t.url %>";
		 if( url.match(/\.(jpeg|jpg|gif|png)$/) != null ){
		     document.getElementById('m_' + "<%= t.id.to_s %>").src = "<%=t.url %>";   
		 }
		 else if(  url.match(/\.(flac|ogg|mp3|wav)$/) != null ){
		     document.getElementById('ma_' + "<%= t.id.to_s %>").src = "<%=t.url %>";
		     document.getElementById('ma_' + "<%= t.id.to_s %>").type = "<%=t.url %>".split('.').pop();
}
   
		     
		</script>
		
		<%= t.option1 %><div style="float=right">
		<%= f.radio_button :answer1, true, :checked => true, class: 'form-control' %>Yes
		<%= f.radio_button :answer1, false,  class: 'form-control'%>No
		</div>
		<br />
		<%= t.option2 %><div style="float=right">
		    <%= f.radio_button :answer2, true, :checked => true, class: 'form-control' %>Yes
		    <%= f.radio_button :answer2, false,  class: 'form-control'%>No
		</div> <br />
		<%= t.option3 %><div style="float=right">
		    <%= f.radio_button :answer3, true, :checked => true, class: 'form-control' %>Yes
		    <%= f.radio_button :answer3, false,  class: 'form-control'%>No
		</div> <br />
		<%= t.option4 %><div style="float=right">
		    <%= f.radio_button :answer4, true, :checked => true, class: 'form-control' %>Yes
		    <%= f.radio_button :answer4, false,  class: 'form-control'%>No
		</div>
		
		<p style="display:none"><%= f.select :multiple_answer_id, [t.id] %></p>
		<p style="display:none"><%= f.select :touch_id, [@touches.id] %></p>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	    <% end %>  
    <% end %>
	</li>
</ul>
</div>
<%= link_to "Back to Genres", "/genres" %>
</div>

</div>

<script>
    func();
</script>

SSAD/Simple-Quiz-Portal/app/views/quizzes/showTopics.html.erb
<% provide(:title, "Genres") %>

<%= link_to "Back to Genres", "/genres" %>
<br/>
<br/>
<ul style="float:left">
    <h1 style="float:left">Genres</h1>
    <% @genre.each do |t| %>
	<li><%= link_to t, "/genres/" + t %></li>
    <% end %>
    <br/>
    <br/>
    <br/>

</ul>
<div id="center3">
<h1>Topics under <%= @head %></h1>
<ul align="center">
<% @genres.each do |t| %>
    <li align="center"><%= link_to t.subtype, "/" + t.parent + "/" + t.subtype %></li>
<% end  %>
</ul>

</div>

SSAD/Simple-Quiz-Portal/app/views/quizzes/updateScore.html.erb
<h1>Quizzes#updateScore</h1>
<p>Find me in app/views/quizzes/updateScore.html.erb</p>