SSAD/Simple-Quiz-Portal/config/routes.rb
Rails.application.routes.draw do
  
  get '/scoreboard', to: 'score_board#show'
  
  post '/retake', to: 'quizzes#retake'
  
  resources :users  
  get '/scores', to: 'leader_boards#showAll'

  get '/genre/:topic', to: 'leader_boards#showGenreWise'

  get '/scores/:id', to: 'leader_boards#showTopicWise'

  get '/genres', to: 'quizzes#showGenres'

  get '/genres/:genre', to: 'quizzes#showTopics'

  get '/:genre/:topic', to: 'quizzes#showQuestions'

  post '/updateScore', to: 'quizzes#updateScore'

  post '/updateMultipleScore', to: 'quizzes#updateMultipleScore'
  
  get '/editdbs', to: 'operations#editDbs'

  post '/addTopic', to: 'operations#addTopic'

  post '/delTopic', to: 'operations#delTopic'

  post '/addSubTopic', to: 'operations#addSubTopic'

  post '/delSubTopic', to: 'operations#delSubTopic'

  post '/addQuestion', to:  'operations#addQuestion'

  post '/delQuestion', to: 'operations#delQuestion'

  post '/addMultipleQuestion', to: 'operations#addMultipleQuestion'

  post '/delMultipleQuestion', to: 'operations#delMultipleQuestion'

  get 'sessions/new'
  
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/google', to: 'sessions#google'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SSAD/Simple-Quiz-Portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
	<!-- Global Site Tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-106736801-1"></script>
	<script src="https://apis.google.com/js/platform.js" async defer></script>
	<meta name="google-signin-client_id" content="257168487550-8pj2nl5fmqvmo6t9cnb4rifd8od4dmcv.apps.googleusercontent.com">

	<script>
	 window.dataLayer = window.dataLayer || [];
	 function gtag(){dataLayer.push(arguments)};
	 gtag('js', new Date());

	 gtag('config', 'UA-106736801-1');
	</script>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
     
    </style>
  </head>

  <body>
      <script>
       function signOut() {
	   var auth2 = gapi.auth2.getAuthInstance();
	   auth2.signOut().then(function () {
	       console.log('User signed out.');
	   });
       }
      </script>
      <header class="navbar navbar-fixed-top navbar-inverse">
	  <div class="container">
	      <nav>
		  <ul id="nav">
		      <% if logged_in? %>
			  <li class="navc" style="background-color:red" >	      <%= link_to "project orange", "/users/" +@user.id.to_s, id: "logo" %></li>
			  <% end %>
		      <% if is_admin?  %>
			  <li class="navc"><%= link_to "Edit DataBase", editdbs_path   %></li>
		      <%end %>
		      <% if logged_in? %>
			  <li class="navc"><%= link_to "Quiz", "/genres" %></li>
			  <li class="navc"><%= link_to "LeaderBoard", "/scores" %></li>
			  <li class="navc"><%= link_to "Profile", current_user %></li>
			  <div style="float:right" >
			      <li class="navc" onclick="signOut()"><%= link_to "Log out", logout_path, method: :delete %></li> </div>
		      <% else %>
			      <li class="navc" style="background-color:red" >	      <%= link_to "project orange", root_path, id: "logo" %></li>

			      <li class="navc"><%= link_to "Home",    root_path %></li>
		      <% end %>
		      <% if !logged_in? %>
			  <div style="float:right" >
			      <li class="navc"><%= link_to "Log in", login_path %></li>
			  </div>
		      <% end  %>
		      

		  </ul>
	      </nav>
	  </div>
      </header>
      <% flash.each do |message_type, message| %>
	  <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
  </body>
</html>